[package]
name = "shogi_kpp_training"
version = "0.1.0"
edition = "2024"

[dependencies]
shogi_core = { version = "0.1.5", features = ["ord"] }
csa = "1.0.2"
anyhow = "1.0"
rayon = "1.5"
rand = "0.8"
rand_distr = "0.4"
ndarray = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
glob = "0.3"
indicatif = "0.17"
flate2 = "1.0"
plotters = "0.3.6"
arrayvec = "0.7.2"
yasai = { git = "https://github.com/sugyan/yasai.git", branch = "main" }
circular-buffer = "1.1.0"

[[bin]]
name = "kpp_learn"
path = "src/kpp_learn.rs"

[[bin]]
name = "kpp_test"
path = "src/kpp_test.rs"

[[bin]]
name = "evaluation_benchmark"
path = "src/evaluation_benchmark.rs"

[[bin]]
name = "shogi_ai"
path = "src/shogi_ai.rs"