[package]
name = "shogi_kpp_training"
version = "0.1.0"
edition = "2024"

[dependencies]
shogi_core = "0.1.5"
csa = "1.0.2"
anyhow = "1.0"
rayon = "1.5"
rand = "0.8"
rand_distr = "0.4"
ndarray = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
glob = "0.3"
indicatif = "0.17"
flate2 = "1.0"
