
name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            usi_engine_artifact_name: usi_engine
            kpp_learn_artifact_name: kpp_learn
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            usi_engine_artifact_name: usi_engine.exe
            kpp_learn_artifact_name: kpp_learn.exe
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev
      - name: Build
        run: cargo build --release --target ${{ matrix.target }} --bin usi_engine --bin kpp_learn
      - name: Rename artifacts
        run: |
          mv target/${{ matrix.target }}/release/${{ matrix.usi_engine_artifact_name }} target/${{ matrix.target }}/release/${{ matrix.usi_engine_artifact_name }}_${{ github.ref_name }}
          mv target/${{ matrix.target }}/release/${{ matrix.kpp_learn_artifact_name }} target/${{ matrix.target }}/release/${{ matrix.kpp_learn_artifact_name }}_${{ github.ref_name }}
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/${{ matrix.usi_engine_artifact_name }}_${{ github.ref_name }}
            target/${{ matrix.target }}/release/${{ matrix.kpp_learn_artifact_name }}_${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
